//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mikano_API.EtisalatMEssagingReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pmmsoapmessenger.com/", ConfigurationName="EtisalatMEssagingReference.MessengerSoap")]
    public interface MessengerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/SendSms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Mikano_API.EtisalatMEssagingReference.SendResult SendSms(Mikano_API.EtisalatMEssagingReference.SoapUser user, string originator, string smsText, string recipientPhone, Mikano_API.EtisalatMEssagingReference.MessageType messageType, string defDate, bool blink, bool flash, bool Private);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/SendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.SendResult> SendSmsAsync(Mikano_API.EtisalatMEssagingReference.SoapUser user, string originator, string smsText, string recipientPhone, Mikano_API.EtisalatMEssagingReference.MessageType messageType, string defDate, bool blink, bool flash, bool Private);
        
        // CODEGEN: Parameter 'recipientPhonesFile' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/SendSms2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Mikano_API.EtisalatMEssagingReference.SendSms2Response SendSms2(Mikano_API.EtisalatMEssagingReference.SendSms2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/SendSms2", ReplyAction="*")]
        System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.SendSms2Response> SendSms2Async(Mikano_API.EtisalatMEssagingReference.SendSms2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/HTTP_SendSms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Mikano_API.EtisalatMEssagingReference.SendResult HTTP_SendSms(int customerID, string userName, string userPassword, string originator, string smsText, string recipientPhone, Mikano_API.EtisalatMEssagingReference.MessageType messageType, string defDate, bool blink, bool flash, bool Private);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/HTTP_SendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.SendResult> HTTP_SendSmsAsync(int customerID, string userName, string userPassword, string originator, string smsText, string recipientPhone, Mikano_API.EtisalatMEssagingReference.MessageType messageType, string defDate, bool blink, bool flash, bool Private);
        
        // CODEGEN: Parameter 'mm7Data' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/SendMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Mikano_API.EtisalatMEssagingReference.SendMMSResponse SendMMS(Mikano_API.EtisalatMEssagingReference.SendMMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/SendMMS", ReplyAction="*")]
        System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.SendMMSResponse> SendMMSAsync(Mikano_API.EtisalatMEssagingReference.SendMMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/SendBinarySms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Mikano_API.EtisalatMEssagingReference.SendResult SendBinarySms(Mikano_API.EtisalatMEssagingReference.SoapUser user, string originator, string binaryBody, string recipientPhone, string defDate, string data_coding, string esm_class, string PID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/SendBinarySms", ReplyAction="*")]
        System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.SendResult> SendBinarySmsAsync(Mikano_API.EtisalatMEssagingReference.SoapUser user, string originator, string binaryBody, string recipientPhone, string defDate, string data_coding, string esm_class, string PID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/HTTP_SendBinarySms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Mikano_API.EtisalatMEssagingReference.SendResult HTTP_SendBinarySms(int customerID, string userName, string userPassword, string originator, string binaryBody, string recipientPhone, string defDate, string data_coding, string esm_class, string PID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/HTTP_SendBinarySms", ReplyAction="*")]
        System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.SendResult> HTTP_SendBinarySmsAsync(int customerID, string userName, string userPassword, string originator, string binaryBody, string recipientPhone, string defDate, string data_coding, string esm_class, string PID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/HTTP_GetSmsStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Mikano_API.EtisalatMEssagingReference.SmsStatus HTTP_GetSmsStatus(int customerID, string userName, string userPassword, string transactionID, bool detailed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/HTTP_GetSmsStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.SmsStatus> HTTP_GetSmsStatusAsync(int customerID, string userName, string userPassword, string transactionID, bool detailed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/GetSmsStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Mikano_API.EtisalatMEssagingReference.SmsStatus GetSmsStatus(Mikano_API.EtisalatMEssagingReference.SoapUser user, string transactionID, bool detailed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/GetSmsStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.SmsStatus> GetSmsStatusAsync(Mikano_API.EtisalatMEssagingReference.SoapUser user, string transactionID, bool detailed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/HTTP_Authenticate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Mikano_API.EtisalatMEssagingReference.AuthResult HTTP_Authenticate(int customerID, string userName, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/HTTP_Authenticate", ReplyAction="*")]
        System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.AuthResult> HTTP_AuthenticateAsync(int customerID, string userName, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/Authenticate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Mikano_API.EtisalatMEssagingReference.AuthResult Authenticate(Mikano_API.EtisalatMEssagingReference.SoapUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/Authenticate", ReplyAction="*")]
        System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.AuthResult> AuthenticateAsync(Mikano_API.EtisalatMEssagingReference.SoapUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/SendServiceSms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Mikano_API.EtisalatMEssagingReference.SendResult SendServiceSms(int customerID, string userName, string userPassword, string originator, string serviceName, string serviceUrl, string recipientPhone, Mikano_API.EtisalatMEssagingReference.MessageType messageType, string defDate, bool blink, bool flash, bool Private);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/SendServiceSms", ReplyAction="*")]
        System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.SendResult> SendServiceSmsAsync(int customerID, string userName, string userPassword, string originator, string serviceName, string serviceUrl, string recipientPhone, Mikano_API.EtisalatMEssagingReference.MessageType messageType, string defDate, bool blink, bool flash, bool Private);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/KeepAlive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Mikano_API.EtisalatMEssagingReference.CommonResult KeepAlive(Mikano_API.EtisalatMEssagingReference.SoapUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/KeepAlive", ReplyAction="*")]
        System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.CommonResult> KeepAliveAsync(Mikano_API.EtisalatMEssagingReference.SoapUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/HTTP_KeepAlive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Mikano_API.EtisalatMEssagingReference.CommonResult HTTP_KeepAlive(int customerID, string userName, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/HTTP_KeepAlive", ReplyAction="*")]
        System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.CommonResult> HTTP_KeepAliveAsync(int customerID, string userName, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/HTTP_InboxProcessing", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode HTTP_InboxProcessing(int customerID, string userName, string userPassword, string operation, string messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/HTTP_InboxProcessing", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> HTTP_InboxProcessingAsync(int customerID, string userName, string userPassword, string operation, string messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/InboxProcessing", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode InboxProcessing(Mikano_API.EtisalatMEssagingReference.SoapUser user, string operation, string messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmmsoapmessenger.com/InboxProcessing", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> InboxProcessingAsync(Mikano_API.EtisalatMEssagingReference.SoapUser user, string operation, string messageId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmmsoapmessenger.com/")]
    public partial class SoapUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int customerIDField;
        
        private string nameField;
        
        private string languageField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SmsStatus))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendMMSResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmmsoapmessenger.com/")]
    public partial class CommonResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmmsoapmessenger.com/")]
    public partial class AuthResult : CommonResult {
        
        private string netPointsField;
        
        private string[] originatorsField;
        
        private int customerIDField;
        
        private string creditSMSField;
        
        private string creditMMSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NetPoints {
            get {
                return this.netPointsField;
            }
            set {
                this.netPointsField = value;
                this.RaisePropertyChanged("NetPoints");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] Originators {
            get {
                return this.originatorsField;
            }
            set {
                this.originatorsField = value;
                this.RaisePropertyChanged("Originators");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CreditSMS {
            get {
                return this.creditSMSField;
            }
            set {
                this.creditSMSField = value;
                this.RaisePropertyChanged("CreditSMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CreditMMS {
            get {
                return this.creditMMSField;
            }
            set {
                this.creditMMSField = value;
                this.RaisePropertyChanged("CreditMMS");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmmsoapmessenger.com/")]
    public partial class SmsStatus : CommonResult {
        
        private System.Xml.XmlNode statisticsField;
        
        private System.Xml.XmlNode detailsField;
        
        private string netPointsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Xml.XmlNode Statistics {
            get {
                return this.statisticsField;
            }
            set {
                this.statisticsField = value;
                this.RaisePropertyChanged("Statistics");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Xml.XmlNode Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
                this.RaisePropertyChanged("Details");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NetPoints {
            get {
                return this.netPointsField;
            }
            set {
                this.netPointsField = value;
                this.RaisePropertyChanged("NetPoints");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendMMSResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmmsoapmessenger.com/")]
    public partial class SendResult : CommonResult {
        
        private string[] rejectedNumbersField;
        
        private string transactionIDField;
        
        private string netPointsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] RejectedNumbers {
            get {
                return this.rejectedNumbersField;
            }
            set {
                this.rejectedNumbersField = value;
                this.RaisePropertyChanged("RejectedNumbers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NetPoints {
            get {
                return this.netPointsField;
            }
            set {
                this.netPointsField = value;
                this.RaisePropertyChanged("NetPoints");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmmsoapmessenger.com/")]
    public partial class SendMMSResult : SendResult {
        
        private string mMWLTransactionIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MMWLTransactionID {
            get {
                return this.mMWLTransactionIDField;
            }
            set {
                this.mMWLTransactionIDField = value;
                this.RaisePropertyChanged("MMWLTransactionID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmmsoapmessenger.com/")]
    public enum MessageType {
        
        /// <remarks/>
        Latin,
        
        /// <remarks/>
        ArabicWithArabicNumbers,
        
        /// <remarks/>
        ArabicWithLatinNumbers,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSms2", WrapperNamespace="http://pmmsoapmessenger.com/", IsWrapped=true)]
    public partial class SendSms2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmmsoapmessenger.com/", Order=0)]
        public Mikano_API.EtisalatMEssagingReference.SoapUser user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmmsoapmessenger.com/", Order=1)]
        public string originator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmmsoapmessenger.com/", Order=2)]
        public string smsText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmmsoapmessenger.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] recipientPhonesFile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmmsoapmessenger.com/", Order=4)]
        public Mikano_API.EtisalatMEssagingReference.MessageType messageType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmmsoapmessenger.com/", Order=5)]
        public string defDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmmsoapmessenger.com/", Order=6)]
        public bool flash;
        
        public SendSms2Request() {
        }
        
        public SendSms2Request(Mikano_API.EtisalatMEssagingReference.SoapUser user, string originator, string smsText, byte[] recipientPhonesFile, Mikano_API.EtisalatMEssagingReference.MessageType messageType, string defDate, bool flash) {
            this.user = user;
            this.originator = originator;
            this.smsText = smsText;
            this.recipientPhonesFile = recipientPhonesFile;
            this.messageType = messageType;
            this.defDate = defDate;
            this.flash = flash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSms2Response", WrapperNamespace="http://pmmsoapmessenger.com/", IsWrapped=true)]
    public partial class SendSms2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmmsoapmessenger.com/", Order=0)]
        public Mikano_API.EtisalatMEssagingReference.SendResult SendSms2Result;
        
        public SendSms2Response() {
        }
        
        public SendSms2Response(Mikano_API.EtisalatMEssagingReference.SendResult SendSms2Result) {
            this.SendSms2Result = SendSms2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMMS", WrapperNamespace="http://pmmsoapmessenger.com/", IsWrapped=true)]
    public partial class SendMMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmmsoapmessenger.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] mm7Data;
        
        public SendMMSRequest() {
        }
        
        public SendMMSRequest(byte[] mm7Data) {
            this.mm7Data = mm7Data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMMSResponse", WrapperNamespace="http://pmmsoapmessenger.com/", IsWrapped=true)]
    public partial class SendMMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmmsoapmessenger.com/", Order=0)]
        public Mikano_API.EtisalatMEssagingReference.SendMMSResult SendMMSResult;
        
        public SendMMSResponse() {
        }
        
        public SendMMSResponse(Mikano_API.EtisalatMEssagingReference.SendMMSResult SendMMSResult) {
            this.SendMMSResult = SendMMSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessengerSoapChannel : Mikano_API.EtisalatMEssagingReference.MessengerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessengerSoapClient : System.ServiceModel.ClientBase<Mikano_API.EtisalatMEssagingReference.MessengerSoap>, Mikano_API.EtisalatMEssagingReference.MessengerSoap {
        
        public MessengerSoapClient() {
        }
        
        public MessengerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessengerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessengerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessengerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Mikano_API.EtisalatMEssagingReference.SendResult SendSms(Mikano_API.EtisalatMEssagingReference.SoapUser user, string originator, string smsText, string recipientPhone, Mikano_API.EtisalatMEssagingReference.MessageType messageType, string defDate, bool blink, bool flash, bool Private) {
            return base.Channel.SendSms(user, originator, smsText, recipientPhone, messageType, defDate, blink, flash, Private);
        }
        
        public System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.SendResult> SendSmsAsync(Mikano_API.EtisalatMEssagingReference.SoapUser user, string originator, string smsText, string recipientPhone, Mikano_API.EtisalatMEssagingReference.MessageType messageType, string defDate, bool blink, bool flash, bool Private) {
            return base.Channel.SendSmsAsync(user, originator, smsText, recipientPhone, messageType, defDate, blink, flash, Private);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mikano_API.EtisalatMEssagingReference.SendSms2Response Mikano_API.EtisalatMEssagingReference.MessengerSoap.SendSms2(Mikano_API.EtisalatMEssagingReference.SendSms2Request request) {
            return base.Channel.SendSms2(request);
        }
        
        public Mikano_API.EtisalatMEssagingReference.SendResult SendSms2(Mikano_API.EtisalatMEssagingReference.SoapUser user, string originator, string smsText, byte[] recipientPhonesFile, Mikano_API.EtisalatMEssagingReference.MessageType messageType, string defDate, bool flash) {
            Mikano_API.EtisalatMEssagingReference.SendSms2Request inValue = new Mikano_API.EtisalatMEssagingReference.SendSms2Request();
            inValue.user = user;
            inValue.originator = originator;
            inValue.smsText = smsText;
            inValue.recipientPhonesFile = recipientPhonesFile;
            inValue.messageType = messageType;
            inValue.defDate = defDate;
            inValue.flash = flash;
            Mikano_API.EtisalatMEssagingReference.SendSms2Response retVal = ((Mikano_API.EtisalatMEssagingReference.MessengerSoap)(this)).SendSms2(inValue);
            return retVal.SendSms2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.SendSms2Response> Mikano_API.EtisalatMEssagingReference.MessengerSoap.SendSms2Async(Mikano_API.EtisalatMEssagingReference.SendSms2Request request) {
            return base.Channel.SendSms2Async(request);
        }
        
        public System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.SendSms2Response> SendSms2Async(Mikano_API.EtisalatMEssagingReference.SoapUser user, string originator, string smsText, byte[] recipientPhonesFile, Mikano_API.EtisalatMEssagingReference.MessageType messageType, string defDate, bool flash) {
            Mikano_API.EtisalatMEssagingReference.SendSms2Request inValue = new Mikano_API.EtisalatMEssagingReference.SendSms2Request();
            inValue.user = user;
            inValue.originator = originator;
            inValue.smsText = smsText;
            inValue.recipientPhonesFile = recipientPhonesFile;
            inValue.messageType = messageType;
            inValue.defDate = defDate;
            inValue.flash = flash;
            return ((Mikano_API.EtisalatMEssagingReference.MessengerSoap)(this)).SendSms2Async(inValue);
        }
        
        public Mikano_API.EtisalatMEssagingReference.SendResult HTTP_SendSms(int customerID, string userName, string userPassword, string originator, string smsText, string recipientPhone, Mikano_API.EtisalatMEssagingReference.MessageType messageType, string defDate, bool blink, bool flash, bool Private) {
            return base.Channel.HTTP_SendSms(customerID, userName, userPassword, originator, smsText, recipientPhone, messageType, defDate, blink, flash, Private);
        }
        
        public System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.SendResult> HTTP_SendSmsAsync(int customerID, string userName, string userPassword, string originator, string smsText, string recipientPhone, Mikano_API.EtisalatMEssagingReference.MessageType messageType, string defDate, bool blink, bool flash, bool Private) {
            return base.Channel.HTTP_SendSmsAsync(customerID, userName, userPassword, originator, smsText, recipientPhone, messageType, defDate, blink, flash, Private);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mikano_API.EtisalatMEssagingReference.SendMMSResponse Mikano_API.EtisalatMEssagingReference.MessengerSoap.SendMMS(Mikano_API.EtisalatMEssagingReference.SendMMSRequest request) {
            return base.Channel.SendMMS(request);
        }
        
        public Mikano_API.EtisalatMEssagingReference.SendMMSResult SendMMS(byte[] mm7Data) {
            Mikano_API.EtisalatMEssagingReference.SendMMSRequest inValue = new Mikano_API.EtisalatMEssagingReference.SendMMSRequest();
            inValue.mm7Data = mm7Data;
            Mikano_API.EtisalatMEssagingReference.SendMMSResponse retVal = ((Mikano_API.EtisalatMEssagingReference.MessengerSoap)(this)).SendMMS(inValue);
            return retVal.SendMMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.SendMMSResponse> Mikano_API.EtisalatMEssagingReference.MessengerSoap.SendMMSAsync(Mikano_API.EtisalatMEssagingReference.SendMMSRequest request) {
            return base.Channel.SendMMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.SendMMSResponse> SendMMSAsync(byte[] mm7Data) {
            Mikano_API.EtisalatMEssagingReference.SendMMSRequest inValue = new Mikano_API.EtisalatMEssagingReference.SendMMSRequest();
            inValue.mm7Data = mm7Data;
            return ((Mikano_API.EtisalatMEssagingReference.MessengerSoap)(this)).SendMMSAsync(inValue);
        }
        
        public Mikano_API.EtisalatMEssagingReference.SendResult SendBinarySms(Mikano_API.EtisalatMEssagingReference.SoapUser user, string originator, string binaryBody, string recipientPhone, string defDate, string data_coding, string esm_class, string PID) {
            return base.Channel.SendBinarySms(user, originator, binaryBody, recipientPhone, defDate, data_coding, esm_class, PID);
        }
        
        public System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.SendResult> SendBinarySmsAsync(Mikano_API.EtisalatMEssagingReference.SoapUser user, string originator, string binaryBody, string recipientPhone, string defDate, string data_coding, string esm_class, string PID) {
            return base.Channel.SendBinarySmsAsync(user, originator, binaryBody, recipientPhone, defDate, data_coding, esm_class, PID);
        }
        
        public Mikano_API.EtisalatMEssagingReference.SendResult HTTP_SendBinarySms(int customerID, string userName, string userPassword, string originator, string binaryBody, string recipientPhone, string defDate, string data_coding, string esm_class, string PID) {
            return base.Channel.HTTP_SendBinarySms(customerID, userName, userPassword, originator, binaryBody, recipientPhone, defDate, data_coding, esm_class, PID);
        }
        
        public System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.SendResult> HTTP_SendBinarySmsAsync(int customerID, string userName, string userPassword, string originator, string binaryBody, string recipientPhone, string defDate, string data_coding, string esm_class, string PID) {
            return base.Channel.HTTP_SendBinarySmsAsync(customerID, userName, userPassword, originator, binaryBody, recipientPhone, defDate, data_coding, esm_class, PID);
        }
        
        public Mikano_API.EtisalatMEssagingReference.SmsStatus HTTP_GetSmsStatus(int customerID, string userName, string userPassword, string transactionID, bool detailed) {
            return base.Channel.HTTP_GetSmsStatus(customerID, userName, userPassword, transactionID, detailed);
        }
        
        public System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.SmsStatus> HTTP_GetSmsStatusAsync(int customerID, string userName, string userPassword, string transactionID, bool detailed) {
            return base.Channel.HTTP_GetSmsStatusAsync(customerID, userName, userPassword, transactionID, detailed);
        }
        
        public Mikano_API.EtisalatMEssagingReference.SmsStatus GetSmsStatus(Mikano_API.EtisalatMEssagingReference.SoapUser user, string transactionID, bool detailed) {
            return base.Channel.GetSmsStatus(user, transactionID, detailed);
        }
        
        public System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.SmsStatus> GetSmsStatusAsync(Mikano_API.EtisalatMEssagingReference.SoapUser user, string transactionID, bool detailed) {
            return base.Channel.GetSmsStatusAsync(user, transactionID, detailed);
        }
        
        public Mikano_API.EtisalatMEssagingReference.AuthResult HTTP_Authenticate(int customerID, string userName, string userPassword) {
            return base.Channel.HTTP_Authenticate(customerID, userName, userPassword);
        }
        
        public System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.AuthResult> HTTP_AuthenticateAsync(int customerID, string userName, string userPassword) {
            return base.Channel.HTTP_AuthenticateAsync(customerID, userName, userPassword);
        }
        
        public Mikano_API.EtisalatMEssagingReference.AuthResult Authenticate(Mikano_API.EtisalatMEssagingReference.SoapUser user) {
            return base.Channel.Authenticate(user);
        }
        
        public System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.AuthResult> AuthenticateAsync(Mikano_API.EtisalatMEssagingReference.SoapUser user) {
            return base.Channel.AuthenticateAsync(user);
        }
        
        public Mikano_API.EtisalatMEssagingReference.SendResult SendServiceSms(int customerID, string userName, string userPassword, string originator, string serviceName, string serviceUrl, string recipientPhone, Mikano_API.EtisalatMEssagingReference.MessageType messageType, string defDate, bool blink, bool flash, bool Private) {
            return base.Channel.SendServiceSms(customerID, userName, userPassword, originator, serviceName, serviceUrl, recipientPhone, messageType, defDate, blink, flash, Private);
        }
        
        public System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.SendResult> SendServiceSmsAsync(int customerID, string userName, string userPassword, string originator, string serviceName, string serviceUrl, string recipientPhone, Mikano_API.EtisalatMEssagingReference.MessageType messageType, string defDate, bool blink, bool flash, bool Private) {
            return base.Channel.SendServiceSmsAsync(customerID, userName, userPassword, originator, serviceName, serviceUrl, recipientPhone, messageType, defDate, blink, flash, Private);
        }
        
        public Mikano_API.EtisalatMEssagingReference.CommonResult KeepAlive(Mikano_API.EtisalatMEssagingReference.SoapUser user) {
            return base.Channel.KeepAlive(user);
        }
        
        public System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.CommonResult> KeepAliveAsync(Mikano_API.EtisalatMEssagingReference.SoapUser user) {
            return base.Channel.KeepAliveAsync(user);
        }
        
        public Mikano_API.EtisalatMEssagingReference.CommonResult HTTP_KeepAlive(int customerID, string userName, string userPassword) {
            return base.Channel.HTTP_KeepAlive(customerID, userName, userPassword);
        }
        
        public System.Threading.Tasks.Task<Mikano_API.EtisalatMEssagingReference.CommonResult> HTTP_KeepAliveAsync(int customerID, string userName, string userPassword) {
            return base.Channel.HTTP_KeepAliveAsync(customerID, userName, userPassword);
        }
        
        public System.Xml.XmlNode HTTP_InboxProcessing(int customerID, string userName, string userPassword, string operation, string messageId) {
            return base.Channel.HTTP_InboxProcessing(customerID, userName, userPassword, operation, messageId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> HTTP_InboxProcessingAsync(int customerID, string userName, string userPassword, string operation, string messageId) {
            return base.Channel.HTTP_InboxProcessingAsync(customerID, userName, userPassword, operation, messageId);
        }
        
        public System.Xml.XmlNode InboxProcessing(Mikano_API.EtisalatMEssagingReference.SoapUser user, string operation, string messageId) {
            return base.Channel.InboxProcessing(user, operation, messageId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> InboxProcessingAsync(Mikano_API.EtisalatMEssagingReference.SoapUser user, string operation, string messageId) {
            return base.Channel.InboxProcessingAsync(user, operation, messageId);
        }
    }
}
